import { createApp } from "vue";
import App from "./App.vue";
import router from "./router/router.js";
import VueSweetalert2 from "vue-sweetalert2";
import "sweetalert2/dist/sweetalert2.min.css";
import { store } from "./data/VueX";
store.dispatch("checkLogin");
const app = createApp(App);
app.use(router).use(VueSweetalert2).use(store);
app.mount("body");
