import { createApp } from "vue";
import App from "./App.vue";
import router from "./router/router.js";
import VueSweetalert2 from "vue-sweetalert2";
import "sweetalert2/dist/sweetalert2.min.css";
import { store } from "./data/VueX";
import vue3lottie from "vue3-lottie";
store.dispatch("checkLogin");
const app = createApp(App);
app.use(VueSweetalert2);
app.use(router);
app.use(store);
app.use(vue3lottie);
app.mount("body");
